export const template_a3 = (years, mb, me, sl, su, tl, tu) =>({
    "inputs":[
      {
          "id":"years",
          "input":{
             "format":{
                "mimeType":"text/plain"
             },
             "value":{
                "inlineValue": years
             }
          }
       },
      {
          "id":"mb",
          "input":{
             "format":{
                "mimeType":"text/plain"
             },
             "value":{
                "inlineValue": mb
             }
          }
       },
      {
          "id":"me",
          "input":{
             "format":{
                "mimeType":"text/plain"
             },
             "value":{
                "inlineValue": me
             }
          }
       },
      {
          "id":"sl",
          "input":{
             "format":{
                "mimeType":"text/plain"
             },
             "value":{
                "inlineValue": sl
             }
          }
       },
       {
        "id":"su",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": su
           }
        }
     },
     {
        "id":"tl",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": tl
           }
        }
     },
     {
        "id":"tu",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": tu
           }
        }
     },
     {
        "id":"kf",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "0.75"
           }
        }
     },
     {
        "id":"o",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "4.5"
           }
        }
     },
     {
        "id":"kr",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "0.5"
           }
        }
     },
     {
        "id":"d",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "-4"
           }
        }
     },
     {
        "id":"token",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "5267228188:AAGx60FtWgHkScBb3ISFL1dp6Oq_9z9z0rw"
           }
        }
     },
     {
        "id":"chat_id",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "-1001773490347"
           }
        }
     },
     {
        "id":"bulletin",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "./output/bulletin.png "
           }
        }
     },
     {
        "id":"method",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "file"
           }
        }
     },  
     {
        "id":"c_lon",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "8.84"
           }
        }
     },
     {
        "id":"c_lat",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "56.75"
           }
        }
     },
     {
        "id":"r_lon",
        "input":{
           "format":{
              "mimeType":"text/plain"
           },
           "value":{
              "inlineValue": "0.66"
           }
        }
     },
    ],
    "outputs":[
       {
          "id":"result",
          "format":{
             "mimeType":"application/binary"
          },
          "transmissionMode":"reference"
       }
    ],
    "response":"document",
    "mode":"async"
 })